name: Scrape Challenge.gov challenges

on:
    push:
        branches:
            - main
    schedule:
        - cron: '16 */2 * * *'
    workflow_dispatch:

jobs:
    scheduled:
        runs-on: ubuntu-latest
        steps:
        - name: Install Go
          uses: actions/setup-go@v2
          with:
              go-version: 1.15.x
        - name: Checkout repo
          uses: actions/checkout@v2
          with:
              fetch-depth: 0
        - name: Use cache
          uses: actions/cache@v2
          with:
              path: |
                  ~/go/pkg/mod # module download cache
                  ~/.cache/go-build # build cache (Linux)
              key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
              restore-keys: |
                  ${{ runner.os }}-go-
        - name: Test
          run: go test ./...
        - name: Run scraper for latest challenges
          run: |-
              go build -o scraper
              ./scraper json > challenges.json
              ./scraper rss < challenges.json > challenges.rss
        - name: Commit and push if changed
          run: |-
              git config user.name "Automated"
              git config user.email "actions@users.noreply.github.com"
              git add -A
              timestamp=$(date -u)
              git commit -m "Updated challenges: ${timestamp}" || exit 0
              git push
