name: Scrape Challenge.gov challenges

on:
    push:
    workflow_dispatch:
    schedule:
        - cron: '15 * * * *'

jobs:
    scheduled:
        runs-on: ubuntu-latest
        steps:
        - name: Install Go
          user: actions/setup-go@v2
          with:
              go-version: 1.15.x
        - name: Checkout repo
          uses: actions/checkout@v2
        - name: Test
          run: go test ./...
        - name: Run scraper for latest challenges
          run: |-
              go run main.go > challenges.json
        - name: Commit and push if changed
          run: |-
              git config user.name "Automated"
              git config user.email "actions@users.noreply.github.com"
              git add -A
              timestamp=$(date -u)
              git commit -m "Updated challenges: ${timestamp}" || exit 0
              git push
